---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: foundationalinfrastructure/gce-cpi-release
inputs:
  - name: bosh-warden-cpi-release

run:
  path: bosh-warden-cpi-release/ci/tasks/clean-orphaned-vms.sh
params:
  google_json_key_data:           replace-me
